fix: add a polyfill to patch Array.prototype.at on emulators
Encountered a problem installing the latest Opal Dev APK on an emulator: pdf.js was throwing `Uncaught TypeError: key.split(...).at is not a function`. Fixed this issue by adding a polyfill that provides the missing `Array.prototype.at` function when it isn't available on a given platform/browser.

See:

* https://github.com/wojtekmaj/react-pdf/issues/1465#issuecomment-1537669572
* https://stackoverflow.com/questions/73194573/why-does-babel-in-create-react-app-not-polyfill-array-prototype-at-properly

See merge request opalmedapps/opal-app#1085